# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8b8fd04075607f1bc7a4eef26719c3908373242b36ee061dc064dc1a7b42d6c8887e726cecb4974540e82e2c0c5d28b00e6bbefa801d2e94f7580a1053270c

test:
  secret_key_base: 98938a503f75c57684a1f49330d05758bfbc48c665ef60019efa17984184cc56914a4e38c6b27f456a440199bf9af6fa7ed44a5739a6cf926854e3f3a5f07948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
